name: projet_login
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Supabase only (auth, db, storage)
  supabase_flutter: ^1.10.23

  # UI et navigation
  flutter_svg: ^2.0.7
  provider: ^6.0.5
  get: ^4.6.5
  shared_preferences: ^2.2.0

  # UI Components
  google_fonts: ^6.2.1
  flutter_screenutil: ^5.8.4
  fluttertoast: ^8.2.2


  # Formulaires et validation
  form_field_validator: ^1.1.0
  email_validator: ^3.0.0

  # Image, HTTP, reconnaissance
  http: ^1.2.1
  image: ^4.1.7
  image_picker: ^1.0.4

  # Sons
  audioplayers: ^5.2.1
  just_audio: ^0.10.3

  # Optionnels pour fichiers/images
  path_provider: ^2.1.1
  mime: ^1.0.4



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/sounds/success.wav
    - assets/sounds/failure.wav

